dist: xenial
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
env:
  - CC=gcc-8 CXX=g++-8
script:
- sudo ln -sf /usr/bin/g++-8 /usr/bin/g++
- sudo ln -sf /usr/bin/gcc-8 /usr/bin/gcc
- cmake -DCMAKE_VERBOSE_MAKEFILE=ON .
- cmake --build .
- ./simple_curl http://www.textfiles.com/virus/virussum.txt
